version: '3.7'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/queueSystem
      - RABBITMQ_URL=amqp://rabbitmq
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:4.2

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
